[Into]
; Pink on dark blue background
text               = d98ba1
subtext            = d7d7d7
nav-active-text    = 131c26
main               = 131c26
sidebar            = 1c2250
player             = 131c26
card               = 131c26z
shadow             = 0e0e13
main-secondary     = 09111b
button             = d98ba1
button-secondary   = d98ba1
button-active      = ff84ac
button-disabled    = 192531
nav-active         = ff84ac
play-button        = d98ba1
tab-active         = 09111b
notification       = 192531
notification-error = 192531
playback-bar       = d98ba1
misc               = FFFFFF


; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous
