# Fonts
font_size 12.5
font_family      Terminess (TTF) Nerd Font Complete Mono
bold_font        Terminess (TTF) Bold Nerd Font Complete Mono
italic_font      Terminess (TTF) Italic Nerd Font Complete Mono
bold_italic_font Terminess (TTF) Bold Italic Nerd Font Complete Mono

# Cursor
cursor_shape underline
cursor #5fd700

# Color Scheme
background #191a21
foreground #b2f7f5
background_opacity 1
tint #C35256

# Color Table
color0 #213296
color8 #213296

color1 #d34148
color9 #f2201f

color2  #C35256
color10 #23fd00

color3  #e67d51
color11 #e67d51

color4  #295890
color12 #1a8fff

color5  #5A6E9D
color13 #65729b

color6  #3daf6d
color14 #14ffff

color7  #edc6ca
color15 #ffffff


# Tabs
tab_bar_edge bottom
tab_bar_style powerline 

scrollback_lines 10000
