[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
#capslock = overload(shift, esc)

# Remaps the escape key to capslock
#esc = capslock

leftshift+leftmeta+f23 = playpause

leftshift = layer(control)

capslock = layer(shift)
