# Hyprland Configuration
# https://wiki.hypr.land/Configuring/

# ==================
# MONITOR CONFIG
# ==================
# Monitors from existing configuration
monitor=,preferred,auto,1

monitor = , preferred,auto,auto

# ==================
# STARTUP APPS
# ==================
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target
exec-once = [workspace 1 silent] thunderbird
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME_QT6,qt6ct

# ==================
# INPUT CONFIG
# ==================
input {
    kb_layout = us
    numlock_by_default = true

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        clickfinger_behavior = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
gesture = 3, up, dispatcher, exec, dms ipc call hypr toggleOverview

gestures {
  workspace_swipe_distance = 300
  workspace_swipe_cancel_ratio = 0.2
  workspace_swipe_min_speed_to_force = 5
}

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = gaming-mouse
    sensitivity = -0.6
    accel_profile = adaptive
}

# ==================
# GENERAL LAYOUT
# ==================
general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2

    layout = dwindle

    allow_tearing = true
}

# ==================
# DECORATION
# ==================
decoration {
    rounding = 12

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 30
        render_power = 5
        offset = 0 5
        color = rgba(00000070)
    }
}

# ==================
# ANIMATIONS
# ==================
animations {
    enabled = true0.5, -0.5, 0.1, 1

    # CURVES
    bezier = overshot, 0.3, 0.99, 0.3, 1.1
    bezier = improved_overshot, 0.3, 1.3, 0.6, 1
    bezier = soft_overshot, 0.4, 0, 0.2, 1.1
    bezier = bounce_approx, 0.34, 1.1, 0.64, 1
    bezier = back_out, 0.34, 1.3, 0.64, 1 
    bezier = back_in, 0.6, -0.28, 0.735, 0.045
    bezier = snap_in, 0.5, -0.5, 0.1, 1

    animation = windowsIn, 1, 5, back_out
    animation = windowsOut, 1, 6, snap_in
    animation = windowsMove, 1, 4, back_out
    animation = fade, 1, 3, default
    animation = border, 1, 3, default
    animation = workspaces, 1, 5, improved_overshot, slide 
}

# ==================
# LAYOUTS
# ==================
dwindle {
    preserve_split = true
}

master {
    mfact = 0.5
}

# ==================
# MISC
# ==================
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 1
}

# ==================
# WINDOW RULES
# ==================
windowrule = tile on, match:class ^(org\.wezfurlong\.wezterm)$

windowrule = rounding 12, match:class ^(org\.gnome\.)

windowrule = tile on, match:class ^(gnome-control-center)$
windowrule = tile on, match:class ^(pavucontrol)$
windowrule = tile on, match:class ^(nm-connection-editor)$

windowrule = float on, match:class ^(gnome-calculator)$
windowrule = float on, match:class ^(galculator)$
windowrule = float on, match:class ^(blueman-manager)$
# windowrule = float on, match:class ^(org\.gnome\.Nautilus)$
windowrule = float on, match:class ^(steam)$
windowrule = float on, match:class ^(xdg-desktop-portal)$

windowrule = float on, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(zoom)$

# Tearing
windowrule = match:class borderlands2.exe, immediate yes
windowrule = match:title ULTRAKILL, immediate yes

# DMS windows floating by default
# ! Hyprland doesn't size these windows correctly so disabling by default here
windowrule = float on, match:class ^(org.quickshell)$

layerrule = no_anim on, match:namespace ^(quickshell)$

source = ./dms/colors.conf
source = ./dms/outputs.conf
source = ./dms/layout.conf
source = ./dms/cursor.conf
source = ./dms/binds.conf
